---
- hosts: 127.0.0.1
  connection: local
  
  tasks:
    - debug: var=secret

    - name: commands
      shell: |
        hostname && whoami
      register: output

    - name: output commands
      debug:
        var: output.stdout_lines
        
