---
- hosts: localhost

  tasks:
    - debug: var=secret
    - debug: var=project
    - debug: var=vm
    - debug: var=vms
    - debug: var=net
    - debug: var=tmp
    - debug: var=cluster_meta
    - debug: var=job_meta
    
    - name: commands
      shell: |
        hostname && whoami

    - name: write tmp/zalupa
      tmp:
        write:
          key: "key"
          value: "value"
