---
- hosts: 127.0.0.1

  tasks:
    - debug: var=secret
    - debug: var=project
    - debug: var=vm
    - debug: var=tmp
    - debug: var=cluster_meta
    
    - name: commands
      shell: |
        hostname && whoami
